apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: micro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-api
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
      - name: api
        env:
        - name: MICRO_ENABLE_STATS
          value: "true"
        args:
        - api
        image: microhq/micro:kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port
