// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"userapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	handler := NewUserHandler(serverCtx)
	server.Use(serverCtx.UserMiddleware.Global)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.UserMiddleware.RegAndLoginHandler,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: handler.Register,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: handler.Login,
			},
		),
	)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/get/:id",
				Handler: handler.GetUser,
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
