// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SmsCode              string   `protobuf:"bytes,3,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegReq) Reset()         { *m = RegReq{} }
func (m *RegReq) String() string { return proto.CompactTextString(m) }
func (*RegReq) ProtoMessage()    {}
func (*RegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *RegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegReq.Unmarshal(m, b)
}
func (m *RegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegReq.Marshal(b, m, deterministic)
}
func (m *RegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegReq.Merge(m, src)
}
func (m *RegReq) XXX_Size() int {
	return xxx_messageInfo_RegReq.Size(m)
}
func (m *RegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegReq proto.InternalMessageInfo

func (m *RegReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegReq) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	ImgCode              string   `protobuf:"bytes,2,opt,name=imgCode,proto3" json:"imgCode,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetImgCode() string {
	if m != nil {
		return m.ImgCode
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegReq)(nil), "go.micro.srv.user.RegReq")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xbf, 0x7c, 0x94, 0x24, 0xdc, 0xc6, 0x09, 0x50, 0x1a, 0x16, 0x94, 0x89, 0xc9, 0x48,
	0xb0, 0xb0, 0xd3, 0x95, 0x25, 0x15, 0x62, 0x44, 0xb4, 0x39, 0x19, 0x4b, 0x38, 0x97, 0xde, 0x25,
	0xf0, 0x3f, 0xf8, 0xc5, 0xc8, 0xae, 0xc3, 0x42, 0x25, 0x16, 0xcb, 0x8f, 0xde, 0xd3, 0xe3, 0x57,
	0x67, 0x38, 0x1f, 0x84, 0x47, 0xbe, 0x99, 0x94, 0x24, 0x1e, 0x26, 0x32, 0x9e, 0x5a, 0x36, 0xde,
	0x6d, 0x85, 0x8d, 0xca, 0x87, 0x09, 0x41, 0xf3, 0x0c, 0x79, 0x4b, 0xb6, 0xa5, 0x1d, 0x5e, 0x40,
	0xee, 0x79, 0xe3, 0xde, 0xa9, 0xca, 0xae, 0xb2, 0xeb, 0x93, 0x36, 0x11, 0xd6, 0x50, 0x0e, 0xaf,
	0xaa, 0x9f, 0x2c, 0x5d, 0xf5, 0x3f, 0x26, 0x3f, 0x8c, 0x4b, 0x28, 0xd5, 0xeb, 0xcb, 0x96, 0x3b,
	0xaa, 0x8e, 0x62, 0x56, 0xa8, 0xd7, 0x07, 0xee, 0xa8, 0x79, 0x84, 0xa2, 0xa5, 0xdd, 0x44, 0x3a,
	0xe2, 0x19, 0x1c, 0x0f, 0x6f, 0xdc, 0xcf, 0xe2, 0x3d, 0x60, 0x05, 0x85, 0xf3, 0x36, 0xcc, 0x26,
	0xed, 0x8c, 0x88, 0xb0, 0x98, 0x26, 0xd7, 0x25, 0x63, 0xbc, 0x37, 0xf7, 0x50, 0xb6, 0xa4, 0x03,
	0xf7, 0x4a, 0xc1, 0x47, 0x22, 0x3d, 0xcf, 0xbe, 0x08, 0xa1, 0x3f, 0x89, 0x78, 0xb5, 0x49, 0x97,
	0xe8, 0xf6, 0x2b, 0x83, 0xc5, 0x93, 0x92, 0xe0, 0x0a, 0x8a, 0x35, 0xf5, 0xdd, 0xda, 0x2b, 0xd6,
	0xe6, 0xd7, 0x26, 0x4c, 0x6a, 0x5b, 0x5f, 0x1e, 0xcc, 0xf6, 0x4f, 0x37, 0xff, 0x70, 0x15, 0x8a,
	0x58, 0xa7, 0x23, 0x09, 0x2e, 0x0f, 0x8e, 0x86, 0x6d, 0xfe, 0x61, 0xd9, 0xe4, 0xf1, 0x43, 0xee,
	0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf1, 0x76, 0x18, 0xa9, 0x01, 0x00, 0x00,
}
