apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: micro-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-web
  template:
    metadata:
      labels:
        name: micro-web
    spec:
      containers:
      - name: web
        env:
        - name: MICRO_ENABLE_STATS
          value: "true"
        args:
        - web
        image: microhq/micro:kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: web-port
