// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test66/test66.proto

package go_micro_srv_test66

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Test66 service

type Test66Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Test66_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Test66_PingPongService, error)
}

type test66Service struct {
	c    client.Client
	name string
}

func NewTest66Service(name string, c client.Client) Test66Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.test66"
	}
	return &test66Service{
		c:    c,
		name: name,
	}
}

func (c *test66Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Test66.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *test66Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Test66_StreamService, error) {
	req := c.c.NewRequest(c.name, "Test66.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &test66ServiceStream{stream}, nil
}

type Test66_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type test66ServiceStream struct {
	stream client.Stream
}

func (x *test66ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *test66ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test66ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test66ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *test66Service) PingPong(ctx context.Context, opts ...client.CallOption) (Test66_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Test66.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &test66ServicePingPong{stream}, nil
}

type Test66_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type test66ServicePingPong struct {
	stream client.Stream
}

func (x *test66ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *test66ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test66ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test66ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *test66ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Test66 service

type Test66Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Test66_StreamStream) error
	PingPong(context.Context, Test66_PingPongStream) error
}

func RegisterTest66Handler(s server.Server, hdlr Test66Handler, opts ...server.HandlerOption) error {
	type test66 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Test66 struct {
		test66
	}
	h := &test66Handler{hdlr}
	return s.Handle(s.NewHandler(&Test66{h}, opts...))
}

type test66Handler struct {
	Test66Handler
}

func (h *test66Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Test66Handler.Call(ctx, in, out)
}

func (h *test66Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Test66Handler.Stream(ctx, m, &test66StreamStream{stream})
}

type Test66_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type test66StreamStream struct {
	stream server.Stream
}

func (x *test66StreamStream) Close() error {
	return x.stream.Close()
}

func (x *test66StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test66StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test66StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *test66Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Test66Handler.PingPong(ctx, &test66PingPongStream{stream})
}

type Test66_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type test66PingPongStream struct {
	stream server.Stream
}

func (x *test66PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *test66PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test66PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test66PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *test66PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
