apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: micro-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-proxy
  template:
    metadata:
      labels:
        name: micro-proxy
    spec:
      containers:
      - name: proxy
        env:
        - name: MICRO_ENABLE_STATS
          value: "true"
        args:
        - proxy
        image: microhq/micro:kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: proxy-port
