apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
  namespace: micro
  labels:
    name: micro-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
    name: micro-proxy
  type: LoadBalancer
