apiVersion: v1
kind: Service
metadata:
  name: micro-web
  namespace: micro
  labels:
    name: micro-web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8082
  selector:
    name: micro-web
  type: LoadBalancer
