apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-web
  template:
    metadata:
      labels:
        name: greeter-web
    spec:
      containers:
        - name: greeter-web
          command: [
		    "/greeter-web"
          ]
          image: microhq/greeter-web:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: web-port
